<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NeutralLanguage>en-US</NeutralLanguage>
    <VersionPrefix>2.2.0</VersionPrefix>
    <AssemblyVersion>2.2.0</AssemblyVersion>
    <FileVersion>2.2.0</FileVersion>
    <Authors>Jaime Olivares, drone1400</Authors>
    <TargetFrameworks>net472;net48;netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>

    <AssemblyTitle>Bzip2</AssemblyTitle>
    <AssemblyName>Bzip2</AssemblyName>

    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Description>A modification of https://github.com/jaime-olivares/bzip2 to compile under net6.0; also adds parallel block compression.</Description>

    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Bzip2.test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <!-- BaseIntermediateOutputPath is set in Directory.Build.props !! -->
    <!-- <BaseIntermediateOutputPath>..\..\output.obj\</BaseIntermediateOutputPath> -->
    <IntermediateOutputPath>..\..\output.obj\$(TargetFramework)_$(Configuration)_$(Platform)\bzip2\</IntermediateOutputPath>
    <OutputPath>..\..\output\$(TargetFramework)_$(Configuration)_$(Platform)\bzip2\</OutputPath>
    <WarningLevel>4</WarningLevel>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\.gitignore" LinkBase=".metadata" />
    <None Include="..\..\.editorconfig" LinkBase=".metadata" />
    <None Include="..\..\LICENSE" LinkBase=".metadata" />
    <None Include="..\..\README.md" LinkBase=".metadata" />
    <None Include="..\..\CHANGELOG" LinkBase=".metadata" />
    <None Include="..\..\doc\**\*.*" LinkBase=".metadata\doc"/>
  </ItemGroup>

</Project>
