<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net472;net48;netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10.0</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <!-- BaseIntermediateOutputPath is set in Directory.Build.props !! -->
        <!-- <BaseIntermediateOutputPath>..\..\output.benchmark.obj\</BaseIntermediateOutputPath> -->
        <IntermediateOutputPath>..\..\output.benchmark.obj\$(TargetFramework)_$(Configuration)_$(Platform)\bzip2\</IntermediateOutputPath>
        <OutputPath>..\..\output.benchmark\$(TargetFramework)_$(Configuration)_$(Platform)\bzip2\</OutputPath>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="SharpCompress" Version="0.42.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\bzip2\Bzip2.csproj" />
    </ItemGroup>

</Project>
